- src/main/java/com/jenkinsci/plugins/badge/dsl/AddShortTextStep.java
no public field ‘link’ (or getter method) found in class com.jenkinsci.plugins.badge.dsl.AddShortTextStep
> Fix JENKINS-53841

- pom.xml
Hacktoberfest contribution to implement [JENKINS-59646](https://issues.jenkins-ci.org/browse/JENKINS-59646) and use GitHub for docs displayed on [plugins.jenkins.io](https://plugins.jenkins.io/badge).  The README already contains excellent documentation, just need this configuration change to use that documentation on plugins.jenkins.io the next time the plugin is released.
> Use GitHub for plugins.jenkins.io documentation

- .github/dependabot.yml
- .mvn/extensions.xml
- .mvn/maven.config
- CONTRIBUTING.md
- README.md
- pom.xml
- src/test/java/com/jenkinsci/plugins/badge/readme/ReadmeGenerator.java
- src/test/resources/readme/README.tmpl
- Use read only URL for SCM connection
- Increase spotbugs effort to detect issues
- Dependabot limit can be removed after Jenkins 2.320
- Allow incremental builds to be deployed
- Remove a Guava usage from test and a deprecation
- Simplify dependency management with plugin bom
- Add CONTRIBUTING file
- Link to plugins page, not GitHub repo
> Use plugin bom

- pom.xml
- src/main/resources/index.jelly
Adds an `index.jelly` and removes `description` from POM – see #55.
----------------
> Add index.jelly

- pom.xml
https://www.jenkins.io/doc/developer/plugin-development/choosing-jenkins-baseline/ recommends either 2.332.4 or 2.346.3.
Also removes the `java.level` property because that is no longer required with the most recent parent pom.
> Require Jenkins 2.346.3 as minimum Jenkins version

- README.md
The examples were wider than necessary so that the reader would see a horizontal scroll bar in the examples.  Examples can be word-wrapped comfortably so that the reader does not need to scroll horizontally to see the example.
Reviewed in the GitHub file viewer
> Improve documentation formatting

- Jenkinsfile
- pom.xml
Better to leave the control of parallel tests to the developer based on their local machine configuration.  Use parallel tests on ci.jenkins.io running one JVM tests process per core.
Confirmed that tests pass with `forkCount=1C` and without it.
> Move parallel test control to Jenkinsfile

- CONTRIBUTING.md
- README.md
- src/main/java/com/jenkinsci/plugins/badge/dsl/AbstractStep.java
- src/test/java/com/jenkinsci/plugins/badge/readme/DescribeStepTag.java
- src/test/resources/readme/README.tmpl
Use generated README with one manual fix.  The manual fix prevents a line from being too long in an example.
Confirmed that the generated README contains only one change that is not workable.  Generated README matches the checked in README except for that one change.
> Improve README generator

- .github/dependabot.yml
- pom.xml
The commons-validator dependency was added in the 1.9.1 release as part of 468a59527a9b906f1790486674b3b6475bf2f4a3, though there seems to have been no references to validator classes in any history of the repository.  It was not includeed in the 1.9 release or any prior releases.
The commons-validator dependency was added to the master branch after the 1.9.1 release as part of 5ca8ab7a3b839c8db1af9ba485754eb81fd6a1e8. There are no references to validator classes in the current source code.
Removing commons-validator reduces the plugin from over 1MB to less than 60KB.  Comparisons are listed below:
```
-rw-rw-r--. 1 mwaite mwaite   54015 Oct 25  2021 ../badge-1.9.hpi
-rw-rw-r--. 1 mwaite mwaite 1135545 Jan 12  2022 ../badge-1.9.1.hpi
-rw-rw-r--. 1 mwaite mwaite   56150 May  4 07:35 …
```
> Remove unused commons-validator dependency

- pom.xml
- src/test/java/com/jenkinsci/plugins/badge/action/AbstractActionTest.java
- src/test/java/com/jenkinsci/plugins/badge/action/BadgeActionTest.java
- src/test/java/com/jenkinsci/plugins/badge/action/ClassHierarchyTest.java
- src/test/java/com/jenkinsci/plugins/badge/dsl/AbstractBadgeTest.java
- src/test/java/com/jenkinsci/plugins/badge/dsl/AddBadgeStepTest.java
- src/test/java/com/jenkinsci/plugins/badge/dsl/AddHtmlBadgeStepTest.java
- src/test/java/com/jenkinsci/plugins/badge/dsl/CreateSummaryStepTest.java
- src/test/java/com/jenkinsci/plugins/badge/dsl/RemoveBadgesStepTest.java
- src/test/java/com/jenkinsci/plugins/badge/dsl/RemoveSummariesStepTest.java
- src/test/java/com/jenkinsci/plugins/badge/dsl/ShortTextStepTest.java
* removed JUnit4 dependency
* migrated namespaces
`mvn clean verify` runs without problems.
```[tasklist]
```
> Upgrade tests to run with JUnit5

- src/test/resources/readme/README.tmpl
The word 'oj' is now 'ok' to be consistent with other examples.
Confirmed that the `mvn clean verify` only made the common changes to the README, without reverting the earlier spelling fix.
```[tasklist]
```
> Fix spelling error in README template

- src/test/java/com/jenkinsci/plugins/badge/action/BadgeActionTest.java
Confirm that JavaScript is discarded by default and is available if the formatting is disabled.
Confirmed tests pass with Java 21 on Linux.
```[tasklist]
```
> Test getText() with isDisableFormatHTML

- src/test/java/com/jenkinsci/plugins/badge/action/BadgeActionTest.java
Test one more method in BadgeAction and one more conditional.
Confirmed tests pass on Linux with Java 21
```[tasklist]
```
> Check link with leading /

- src/main/java/com/jenkinsci/plugins/badge/BadgePlugin.java
- src/main/java/com/jenkinsci/plugins/badge/action/BadgeAction.java
- src/main/java/com/jenkinsci/plugins/badge/action/BadgeSummaryAction.java
- src/main/java/com/jenkinsci/plugins/badge/action/HtmlBadgeAction.java
- src/main/resources/com/jenkinsci/plugins/badge/BadgePlugin/help-formatter.html
Improve the global configuration page and corresponsing code.
* Move to Security tab  -> up for discussion, however I think right now it belongs there
* Clearer description of config options -> I found `Disable OWASP Markup Formatter` and `If checked, HTML content will not be formatted according OWASP in badges and summary` not really helpful as the abbreviation OWASP may not be known to everyone
* Remove dead / outdated / unneeded code in BadgePlugin
Verified configuration is still working and visually pleasing: 
```[tasklist]
```
> Improve global configuration

- src/main/java/com/jenkinsci/plugins/badge/action/BadgeAction.java
- src/main/resources/com/jenkinsci/plugins/badge/action/BadgeAction/badge.jelly
- src/test/java/com/jenkinsci/plugins/badge/action/BadgeActionTest.java
Symbols do not require height or width but icons without height and width will render at their original size instead of rendering at the standard size for icons.
Fixes https://github.com/jenkinsci/badge-plugin/issues/148
Confirmed that **before** this change, the following icon renders incorrectly as a 48x48 image:
```
addBadge(icon: '/images/48x48/light-grey.gif', text: 'large icon')
```
Confirmed that **before** this change, the following icon renders correctly:
```
addBadge(icon: 'symbol-star plugin-ionicons-api', text: 'a starred build')
```
Confirmed that **after** this change, the following icon renders correctly as a 16x16 image:
```
addBadge(icon: '/images/48x48/light-grey.gif', text: 'large icon')
```
Confirmed that **after** this change, the following icon renders correctly:
``` …
```
> Use size class for all icons, not just symbols

- src/main/resources/com/jenkinsci/plugins/badge/action/BadgeAction/badge.jelly
Fixes #148 by hard-coding the icon style to include `width: 16px; height: 16px;`
I also removed the no longer existing references to the `badge-shortText` css classes (removed in https://github.com/jenkinsci/badge-plugin/pull/153/) and therefore the usage of `badgeClass` alltogether.
~~Further I changed the "default" css style for text badges to not be `"border: solid"` anymore - I am pretty sure this was not intended.~~
Manually verified badges look as expected.
> Hard-code size of icons (#148)

- pom.xml
- src/main/java/com/jenkinsci/plugins/badge/dsl/AbstractAddBadgeStep.java
- src/main/java/com/jenkinsci/plugins/badge/dsl/AbstractRemoveBadgesStep.java
- src/main/java/com/jenkinsci/plugins/badge/dsl/AddBadgeStep.java
- src/main/java/com/jenkinsci/plugins/badge/dsl/AddErrorBadgeStep.java
- src/main/java/com/jenkinsci/plugins/badge/dsl/AddInfoBadgeStep.java
- src/main/java/com/jenkinsci/plugins/badge/dsl/AddSummaryStep.java
- src/main/java/com/jenkinsci/plugins/badge/dsl/AddWarningBadgeStep.java
- src/main/java/com/jenkinsci/plugins/badge/dsl/RemoveBadgesStep.java
- src/main/java/com/jenkinsci/plugins/badge/dsl/RemoveSummariesStep.java
- src/test/java/com/jenkinsci/plugins/badge/dsl/AbstractAddBadgeStepTest.java
- src/test/java/com/jenkinsci/plugins/badge/dsl/AbstractRemoveBadgeStepTest.java
- src/test/java/com/jenkinsci/plugins/badge/dsl/AddBadgeStepTest.java
- src/test/java/com/jenkinsci/plugins/badge/dsl/AddErrorBadgeStepTest.java
- src/test/java/com/jenkinsci/plugins/badge/dsl/AddInfoBadgeStepTest.java
- src/test/java/com/jenkinsci/plugins/badge/dsl/AddSummaryStepTest.java
- src/test/java/com/jenkinsci/plugins/badge/dsl/AddWarningBadgeStepTest.java
- src/test/java/com/jenkinsci/plugins/badge/dsl/LegacyPipelineTest.java
- src/test/java/com/jenkinsci/plugins/badge/dsl/RemoveBadgesStepTest.java
- src/test/java/com/jenkinsci/plugins/badge/dsl/RemoveSummariesStepTest.java
See #187 
Added `@DataBoundConstructor` and `@DataBoundSetter` as appropriate to allow fields to be optional.
Manually tested with declarative pipeline and also added new tests for it.
> Allow fields to be optional in declarative pipeline

- src/main/java/com/jenkinsci/plugins/badge/dsl/AddBadgeStep.java
- src/main/java/com/jenkinsci/plugins/badge/dsl/AddHtmlBadgeStep.java
- src/main/java/com/jenkinsci/plugins/badge/dsl/AddShortTextStep.java
- src/main/java/com/jenkinsci/plugins/badge/dsl/CreateSummaryStep.java
- src/main/java/com/jenkinsci/plugins/badge/dsl/RemoveHtmlBadgesStep.java
- src/main/resources/com/jenkinsci/plugins/badge/dsl/AddHtmlBadgeStep/help.html
- src/main/resources/com/jenkinsci/plugins/badge/dsl/AddShortTextStep/help.html
- src/main/resources/com/jenkinsci/plugins/badge/dsl/CreateSummaryStep/help.html
- src/main/resources/com/jenkinsci/plugins/badge/dsl/RemoveHtmlBadgesStep/help.html
- src/test/java/com/jenkinsci/plugins/badge/dsl/AddBadgeStepTest.java
- src/test/java/com/jenkinsci/plugins/badge/dsl/AddHtmlBadgeStepTest.java
- src/test/java/com/jenkinsci/plugins/badge/dsl/CreateSummaryStepTest.java
- src/test/java/com/jenkinsci/plugins/badge/dsl/RemoveHtmlBadgesStepTest.java
- src/test/java/com/jenkinsci/plugins/badge/dsl/ShortTextStepTest.java
Fixes #198 
The deprecated `color` field was missing its getter and caused the snippet generation to fail.
The getter was restored and maps to the new `style` field - similar to the setter.
While at it I also moved the deprecated pipeline steps to the "Advanced / Deprecated" section and added a help text to make users aware of the deprecation and replacement steps.
Manually checked that all pipeline steps generate as expected.
> Fix pipeline syntax snippet generation (#198)

- src/main/resources/com/jenkinsci/plugins/badge/action/BadgeAction/badge.jelly
- src/main/resources/com/jenkinsci/plugins/badge/assets.css
- src/main/resources/com/jenkinsci/plugins/badge/dsl/AddBadgeStep/help-cssClass.html
- src/main/resources/com/jenkinsci/plugins/badge/dsl/AddBadgeStep/help.html
Restores stylized text only badges lost in 2.0 refactor. Text only badges (no icon or link) will render with rounded corners and default background color that matches the text color but with some opacity.
Before:
After:
> Provide built-in css classes for text badges

- src/main/java/com/jenkinsci/plugins/badge/action/AbstractBadgeAction.java
- src/main/java/com/jenkinsci/plugins/badge/dsl/AddBadgeStep.java
- src/main/java/com/jenkinsci/plugins/badge/dsl/AddShortTextStep.java
- src/test/java/com/jenkinsci/plugins/badge/dsl/LegacyPipelineTest.java
This change improves the backwards compatibility for legacy badge color references that are not jenkins color classes. Colors that reference defined jenkins palette or semantic names are converted to their respective css variable references.
> Backwards compatibility for color references

- .github/workflows/codecov.yml
- src/main/java/com/jenkinsci/plugins/badge/action/AbstractBadgeAction.java
- src/main/java/com/jenkinsci/plugins/badge/action/BadgeSummaryAction.java
- src/main/java/com/jenkinsci/plugins/badge/dsl/AbstractAddBadgeStep.java
- src/main/java/com/jenkinsci/plugins/badge/dsl/AbstractRemoveBadgesStep.java
- src/main/java/com/jenkinsci/plugins/badge/dsl/AddHtmlBadgeStep.java
- src/main/java/com/jenkinsci/plugins/badge/dsl/AddShortTextStep.java
- src/main/java/com/jenkinsci/plugins/badge/dsl/CreateSummaryStep.java
- src/main/java/com/jenkinsci/plugins/badge/dsl/RemoveHtmlBadgesStep.java
- src/test/java/com/jenkinsci/plugins/badge/dsl/AddBadgeStepTest.java
- src/test/java/com/jenkinsci/plugins/badge/dsl/CreateSummaryStepTest.java
- src/test/java/com/jenkinsci/plugins/badge/dsl/RemoveBadgesStepTest.java
- src/test/java/com/jenkinsci/plugins/badge/dsl/ShortTextStepTest.java
Following #202 I found some more improvements to the codebase
* refine codecov action
* use java 17 features
Delegated to CI.
> Minor code improvements

- src/main/java/com/jenkinsci/plugins/badge/action/AbstractBadgeAction.java
- src/main/java/com/jenkinsci/plugins/badge/action/BadgeSummaryAction.java
- src/main/resources/com/jenkinsci/plugins/badge/action/BadgeSummaryAction/summary.jelly
- src/test/java/com/jenkinsci/plugins/badge/action/ActionClassHierarchyTest.java
- src/test/java/com/jenkinsci/plugins/badge/action/BadgeSummaryActionTest.java
- src/test/java/com/jenkinsci/plugins/badge/dsl/AbstractRemoveBadgesStepTest.java
- src/test/java/com/jenkinsci/plugins/badge/dsl/AddSummaryStepTest.java
- src/test/java/com/jenkinsci/plugins/badge/dsl/RemoveBadgesStepTest.java
- src/test/java/com/jenkinsci/plugins/badge/dsl/StepClassHierarchyTest.java
- src/test/java/com/jenkinsci/plugins/badge/dsl/UITest.java
Following on https://github.com/jenkinsci/badge-plugin/pull/210#issuecomment-2477222578 this PR aims to introduce UI tests.
While implementing those tests I noticed that summaries without an icon are currently "omitted" without any notice. As the jelly tag `summary` that we use requires a value I added a fallback that will return the `emtpy.png` from jenkins core alongside logging a warning. This allows us to create "text-only" summaries.
`mvn clean verify`
> Introduce UI tests

- pom.xml
- src/main/java/com/jenkinsci/plugins/badge/action/AbstractBadgeAction.java
- src/main/java/com/jenkinsci/plugins/badge/action/BadgeSummaryAction.java
- src/main/java/com/jenkinsci/plugins/badge/dsl/AbstractAddBadgeStep.java
- src/main/java/com/jenkinsci/plugins/badge/dsl/AbstractRemoveBadgesStep.java
- src/main/java/com/jenkinsci/plugins/badge/dsl/AddBadgeStep.java
- src/main/java/com/jenkinsci/plugins/badge/dsl/AddErrorBadgeStep.java
- src/main/java/com/jenkinsci/plugins/badge/dsl/AddInfoBadgeStep.java
- src/main/java/com/jenkinsci/plugins/badge/dsl/AddWarningBadgeStep.java
- src/main/java/com/jenkinsci/plugins/badge/dsl/CreateSummaryStep.java
- src/test/java/com/jenkinsci/plugins/badge/dsl/UITest.java
Migrate from deprecated/EOL Commons Lang 2 to Commons Lang 3.
`mvn clean verify`
> Upgrade Commons Lang from 2 to 3

- src/main/resources/com/jenkinsci/plugins/badge/assets.css
Fixes https://github.com/jenkinsci/badge-plugin/issues/276
I did not find any issues with adding the styles mentioned in https://github.com/jenkinsci/badge-plugin/issues/276#issuecomment-3031166868 to the shipped CSS classes. 
However, it's hard to tell for me if this causes changes for users that could considered regression rather than improvements. Any feedback from @jenkinsci/badge-plugin-developers would be great.
Manual testing.
> Improve overflow behavior for text badges
